services:
  mongo:
    build: ./mongo_rs
    container_name: mongo-db
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
      MONGO_REPLICA_HOST: mongo-db
      MONGO_REPLICA_PORT: 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mongodb://mongo-db:27017/playDB?authSource=admin&replicaSet=rs0"
    depends_on:
      - mongo
    command: ["npm", "run", "start"]
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
